pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
CI proof in https://github.com/openshift/origin/pull/24089 - green e2e in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/24089/pull-ci-openshift-origin-master-e2e-gcp/3564
/cc @adambkaplan @soltysh
=> Bug 1768877: Fix image lookup for ReplicaSets and DaemonSets in app group

pkg/admission/imagepolicy/imagereferencemutators/pods.go
=> Bug 1801095: add all supported versions for pod mutators

Makefile, OWNERS, pkg/admission/imagepolicy/accept.go, pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go, pkg/admission/imagepolicy/imagereferencemutators/meta.go, pkg/admission/imagepolicy/imagereferencemutators/pods.go, pkg/admission/imagepolicy/imagereferencemutators/pods_test.go
/cc @soltysh @adambkaplan @smarterclayton 
/hold
for proof in https://github.com/openshift/origin/pull/24530
=> Bug 1801095: Fix imagepolicyresolve plugin to resolve when enabled on an existing object

pkg/apivalidation/uservalidation.go
=> add validation functions for usernames and groupnames

pkg/securitycontextconstraints/sccmatching/provider.go
This is a proposal.
It is the counterpart of the following from the pod validation in upstream:
```golang
if sc.AllowPrivilegeEscalation != nil && !*sc.AllowPrivilegeEscalation {
if sc.Privileged != nil && *sc.Privileged {
allErrs = append(allErrs, field.Invalid(fldPath, sc, "cannot set `allowPrivilegeEscalation` to false and `privileged` to true"))
}
if sc.Capabilities != nil {
for _, cap := range sc.Capabilities.Add {
if string(cap) == "CAP_SYS_ADMIN" {
allErrs = append(allErrs, field.Invalid(fldPath, sc, "cannot set `allowPrivilegeEscalation` to false and `capabilities.Add` CAP_SYS_ADMIN"))
}
}
}
}
```
=> Bug 1934400: scc-admission: don't apply defaultAllowPrivilegeEscalation:false when container is privileged

pkg/admission/imagepolicy/accept.go, pkg/admission/imagepolicy/imagepolicy.go, pkg/admission/imagepolicy/imagepolicy_test.go
backport of https://github.com/openshift/apiserver-library-go/pull/50
=> Bug 1981770: fix Deployment creates a huge number of ReplicaSets

pkg/admission/imagepolicy/accept.go, pkg/admission/imagepolicy/imagepolicy.go, pkg/admission/imagepolicy/imagepolicy_test.go
=> Bug 1981775: fix Deployment creates a huge number of ReplicaSets

pkg/admission/imagepolicy/accept.go, pkg/admission/imagepolicy/imagepolicy.go, pkg/admission/imagepolicy/imagepolicy_test.go
=> Bug 1981784: fix Deployment creates a huge number of ReplicaSets

pkg/securitycontextconstraints/sccadmission/admission.go, pkg/securitycontextconstraints/sccadmission/admission_test.go, pkg/securitycontextconstraints/sccadmission/scc_exec_test.go, pkg/securitycontextconstraints/sccmatching/matcher.go
=> [release-4.9] Bug 2017020: backport SCC fixes

pkg/securitycontextconstraints/sccadmission/admission.go, pkg/securitycontextconstraints/sccadmission/admission_test.go, pkg/securitycontextconstraints/sccadmission/scc_exec_test.go, pkg/securitycontextconstraints/sccmatching/matcher.go
=> [release-4.8] Bug 2017027: backport SCC fixes

pkg/securitycontextconstraints/sccadmission/admission.go
=> expect new more restrictive SCCs

go.mod, pkg/securitycontextconstraints/sccadmission/admission.go, pkg/securitycontextconstraints/sccadmission/admission_test.go
add message about working with restricted, but not restricted-v2
/assign @stlaz
=> bug 2117374: add message about working with restricted, but not restricted-v2

pkg/securitycontextconstraints/seccomp/strategy.go, pkg/securitycontextconstraints/seccomp/strategy_test.go
=> OCPBUGS-6030: sccadmission: use the actual pod/container seccomp profile to match SCC

go.mod, pkg/securitycontextconstraints/sccadmission/admission.go, pkg/securitycontextconstraints/sccadmission/admission_test.go, vendor/modules.txt
This is a manual backport of https://github.com/openshift/apiserver-library-go/pull/89
/cc @deads2k @ibihim
=> OCPBUGS-6683: add message about working with restricted, but not restricted-v2

go.mod, pkg/securitycontextconstraints/sccmatching/patched_sc_accessors.go, pkg/securitycontextconstraints/sccmatching/provider.go, pkg/securitycontextconstraints/sccmatching/provider_test.go
backport of https://github.com/openshift/apiserver-library-go/pull/100
/assign @ibihim
=> OCPBUGS-7268: Add SeccompProfile field if the annotation is specified

pkg/securitycontextconstraints/sccadmission/admission.go, pkg/securitycontextconstraints/sccadmission/admission_test.go, pkg/securitycontextconstraints/sccmatching/matcher.go, pkg/securitycontextconstraints/sccmatching/provider.go, vendor/k8s.io/kubernetes/pkg/apis/core/pods/helpers.go, vendor/k8s.io/kubernetes/pkg/fieldpath/doc.go, vendor/k8s.io/kubernetes/pkg/fieldpath/fieldpath.go, vendor/modules.txt
=> securitycontextconstraints: handle ephemeral containers

pkg/securitycontextconstraints/sccadmission/admission.go, pkg/securitycontextconstraints/sccadmission/admission_test.go, pkg/securitycontextconstraints/sccmatching/matcher.go, pkg/securitycontextconstraints/sccmatching/provider.go
backport of https://github.com/openshift/apiserver-library-go/pull/110
/cc @deads2k
=> [4.13] handle ephemeral containers

pkg/securitycontextconstraints/sccadmission/admission.go, pkg/securitycontextconstraints/sccadmission/admission_test.go, pkg/securitycontextconstraints/sccmatching/matcher.go, pkg/securitycontextconstraints/sccmatching/provider.go
backport of #110  with conflicts resolved around computeSecurityContext() function formatting in pkg/securitycontextconstraints/sccadmission/admission.go
/assign @s-urbaniak
=> [4.12] OCPBUGS-8737: handle ephemeral containers

pkg/securitycontextconstraints/sccadmission/admission.go, pkg/securitycontextconstraints/sccadmission/admission_test.go, pkg/securitycontextconstraints/sccmatching/matcher.go, pkg/securitycontextconstraints/sccmatching/provider.go
backport of #112 
/assign @s-urbaniak
=> [4.11] OCPBUGS-8736: handle ephemeral containers

pkg/securitycontextconstraints/sccadmission/admission.go, pkg/securitycontextconstraints/sccadmission/admission_test.go
/cc @openshift/openshift-team-auth 
/cc @dpuniaredhat
=> OCPBUGS-17119: scc: required-SCC - use direct cache retrieval

OWNERS
=> NO-JIRA: Expand approvers for apiserver-library-go

pkg/securitycontextconstraints/sccmatching/provider.go, pkg/securitycontextconstraints/sccmatching/provider_test.go
according to https://github.com/openshift/enhancements/blob/master/enhancements/kubelet/user-namespaces-support.md
=> OCPNODE-2553: add support for UserNamespaceLevel field
