openshift/apiserver-library-go

pkg/authorization/scope/converter.go

This is used in admitting Services with external IPs that reach
outside the allowed IP range.
/assign @deads2k

Bug 1757553: Add service with network.openshift.io group as escalating

---

pkg/authorization/scope/converter.go

This is used in admitting Services with external IPs that reach
outside the allowed IP range.

Bug 1757553: Escalating external ip 1.17.0 beta.2

---

pkg/authorization/scope/converter.go

The externalIP admission actually uses the externalips subresource
so the current escalating rules cleanup would ignore that.

Bug 1779694: fix the externalIP scope escalation

---

pkg/securitycontextconstraints/sccadmission/admission.go
pkg/securitycontextconstraints/sccadmission/admission_test.go
pkg/securitycontextconstraints/sccadmission/scc_exec_test.go

Cherry pick of https://github.com/openshift/apiserver-library-go/pull/20.
[Bug 1793587](https://bugzilla.redhat.com/show_bug.cgi?id=1793587) - sccadmission plugin incorrectly reports "no SecurityContextConstraints found in xxx"

[release-4.3] Bug 1793587: sccadmission plugin incorrectly reports "no SecurityContextConstraints found in xxx"

---

pkg/securitycontextconstraints/capabilities/mustrunas.go
pkg/securitycontextconstraints/capabilities/mustrunas_test.go
pkg/securitycontextconstraints/capabilities/types.go
pkg/securitycontextconstraints/group/mustrunas.go
pkg/securitycontextconstraints/group/mustrunas_test.go
pkg/securitycontextconstraints/group/runasany.go
pkg/securitycontextconstraints/group/runasany_test.go
pkg/securitycontextconstraints/group/types.go
pkg/securitycontextconstraints/sccmatching/provider.go

This fixes three issues in the error messages produced by the SCC validation:
- "securityContext" field is repeated in runAsUser validation message
- capabilities validation doesn't indicate the container the error applies to
- fsGroup/supplementalGroups doesn't indicate the full path (e.g. spec.securityContext.fsGroup)

Fix field paths in SCC validation error messages

---

pkg/securitycontextconstraints/sccadmission/admission.go
pkg/securitycontextconstraints/sccmatching/provider.go
pkg/securitycontextconstraints/sccmatching/types.go
pkg/securitycontextconstraints/util/sort/bypriority.go
pkg/securitycontextconstraints/util/sort/byrestrictions.go
pkg/securitycontextconstraints/util/sort/byrestrictions_test.go

- `securityserviceconstraints.admission.k8s.io/denied: restrictive,privileged`
- `securitycontextconstraints.admission.k8s.io/too-restrictive-foo: <validation-errors>`, e.g.:
```
"securitycontextconstraints.admission.k8s.io/too-restrictive-anyuid": "[spec.volumes[6]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used, spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed, spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]",
```
- `securitycontextconstraints.admission.k8s.io/reason: "foo" is most restrictive, not denied, and chosen over "bar" because "foo" forbids host networking`.

scc-admission: add audit annotations with reason

---

pkg/securitycontextconstraints/sccadmission/admission.go

Adds messages so we can see all the SCCs we attempted to use to diagnose errors like https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-serial-4.8/1361322244994764800

indicate every attempted security context constraint

---

pkg/labelselector/labelselector.go
pkg/labelselector/labelselector_test.go

Moves the code here to be used by openshift-apiserver and kube-apiserver.
And fixing the given bug.

Bug 1923847: labelselector: fix empty value parsing

---

pkg/securitycontextconstraints/sccmatching/matcher.go
pkg/securitycontextconstraints/util/sort/byrestrictions.go
pkg/securitycontextconstraints/util/sort/byrestrictions_test.go

To generate a reason message we rely on the fact that point groups are not overflowing.
However, the current numbering does not respect the fact that runAs* points are counted twice,
once for RunAsUser and once for SELinuxContext constraints.
This fixes it by shifting the numbers to account for selinux runAs* point scores.
/cc @deads2k @mfojtik @sttts

Bug 1996646: pkg/securitycontextconstraints: fix points groups

---

pkg/admission/quota/clusterresourcequota/admission.go

- some of the namespaced objects (eg CRDs) were being ignored due to
not being of type ObjectMetaAccessor
- this was causing over logging ~so logging level was decreased~

Bug 1965368: fix clusterresourcequota admission

---

pkg/securitycontextconstraints/sccadmission/admission.go
pkg/securitycontextconstraints/sccadmission/admission_test.go

holds SCC admission for the force-created SCCs to be present before evaluation.  Provides a unique error message if it fails.
/hold for proof.

require standard SCCs before evaluating SCC admission

---

pkg/securitycontextconstraints/sccmatching/matcher.go
pkg/securitycontextconstraints/sccmatching/matcher_test.go

kube 1.23 turns the ephemeralContainers feature "on" by default,
add this podSpec field to SCC admission to prevent privilege escalation.
/cc @deads2k 
---
edit: the feature gets turned on by default in
https://github.com/kubernetes/kubernetes/pull/105405/files#diff-71e3b98f9a6bbf5b8421e26a7ba0c079f397cd8d49abacdad943c66a4f44f03dR795

Bug 2023342: scc admission: add ephemeralContainers to admission consideration

---

pkg/authorization/OWNERS
pkg/securitycontextconstraints/OWNERS

The auth team owns the SCCs and the scope authorizer, they should be at least reviewers there.
/cc @s-urbaniak 
/cc @deads2k

scc, scope authorizer: add the auth team ownership

---

pkg/securitycontextconstraints/sccadmission/admission.go
pkg/securitycontextconstraints/sccadmission/admission_test.go

Ignore non-linux pods while applying SCCs

Bug 2079965: Ignore non-linux pods while applying SCCs

---

pkg/securitycontextconstraints/sccadmission/admission_test.go
pkg/securitycontextconstraints/sccmatching/provider.go
pkg/securitycontextconstraints/sccmatching/provider_test.go

PodSecurity admission requires the non-zero flag to be set no matter
the container/pod UID.
/assign @deads2k

Bug 2086519: scc: set container nonroot=true if the pod/container RunAsUser is non-zero

---

pkg/admission/quota/clusterresourcequota/admission.go

Include the accessor namespace and name in the error when Validate fails due to 'caches not synchronized'

Bug 2093440: include pluginName in caches not syncd error

---

pkg/securitycontextconstraints/sccadmission/admission.go
pkg/securitycontextconstraints/sccadmission/admission_test.go
pkg/securitycontextconstraints/sccadmission/scc_exec.go
pkg/securitycontextconstraints/sccadmission/scc_exec_test.go
pkg/securitycontextconstraints/sccmatching/matcher.go

needed before merging the PSA workload type warning fixes in https://github.com/openshift/kubernetes/pull/1393
This has always been inefficient, causing a live namespace lookup for every pod create, but on updates I think we were smart enough to avoid the lookup.  The o/k PR causes this lookup to happen on every workload resource mutation, so it's very expensive.  This change switches us to use the cached namespaces and potentially wait up to 10s (the old value as well) for the cache to catch up and have the proper annotations.
/assign @stlaz

use cached namespaces instead of live lookups for UID ranges

---

go.mod
go.sum
pkg/securitycontextconstraints/sccadmission/admission.go
pkg/securitycontextconstraints/sccadmission/admission_test.go
pkg/securitycontextconstraints/sccmatching/matcher.go
pkg/securitycontextconstraints/sccmatching/provider.go
vendor/k8s.io/kubernetes/pkg/apis/core/pods/helpers.go
vendor/k8s.io/kubernetes/pkg/fieldpath/doc.go
vendor/k8s.io/kubernetes/pkg/fieldpath/fieldpath.go
vendor/modules.txt

cherry-pick of #113
Conflict resolution:
- remove tests specific to Linux/Windows OS fields - the field was not present
- vendor in podhelpers to walk containers
/assign @deads2k 
We'll need approval for the go.mod changes
The vbom is necessary because of library-go@release-4.10

[4.10] handle ephemeral containers

---

pkg/securitycontextconstraints/sccadmission/admission.go

This is scavanging a small portion of https://github.com/openshift/apiserver-library-go/pull/107 where `FindApplicableSCCs` is invoked with the requested namespace but without a user. Hence, the current logic returns all SCCs. This indirection makes the current code hard to read.
This PR suggests to simplify it and list all SCCs instead which is the same logic.
/cc @stlaz

pkg/securitycontextconstraints/sccadmission: simplify retrieving SCCs

---

pkg/securitycontextconstraints/sccadmission/admission.go
pkg/securitycontextconstraints/sccadmission/admission_test.go

This PR introduces a list of known informative annotations; pod admission then will ignore any pod mutations that only add these annotations.
The goal is to prevent a pod to be re-admitted and potentially change the SCC under which it gets admitted when a mutation only adds informative annotations, which shouldn't cause SCC changes.
This also fixes a bug in the `TestShouldIgnore` unit test within `pkg/securitycontextconstraints/sccadmission/admission_test.go`.

OCPBUGS-11933: Ignore informative annotations upon admission

---

pkg/securitycontextconstraints/sysctl/mustmatchpatterns.go

As part of Kubernetes v1.29, several sysctls [1] have been added to the SafeSysctlAllowlist. However, that list has not yet been updated in OCP. This change addresses that issue.
[1] https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#safe-and-unsafe-sysctls

NO-JIRA: pkg: add missing safe sysctls to the list of SafeSysctlAllowlist

---

pkg/securitycontextconstraints/sysctl/mustmatchpatterns.go

As part of Kubernetes v1.29, several sysctls [1] have been added to the SafeSysctlAllowlist. However, that list has not yet been updated in OCP. This change addresses that issue.
[1] https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#safe-and-unsafe-sysctls

OCPBUGS-42019:[release-4.17] pkg: add missing safe sysctls to the list of SafeSysctlAllowlist

---

pkg/securitycontextconstraints/OWNERS

- Remove non-Red-Hatters.
- Add @liouk as reviewer.
- Bump me (@ibihim) to approver.
Reflect current ownership status.

pkg/scc: update current SCC owners

---

pkg/securitycontextconstraints/sccadmission/admission.go
pkg/securitycontextconstraints/sccadmission/admission_test.go
pkg/securitycontextconstraints/sccadmission/scc_authz_check.go
pkg/securitycontextconstraints/sccadmission/scc_authz_check_test.go

- Add annotation for "SCC is allowed for {user / serviceaccount}"
- Minor refactoring
- Bump deprecated functions
Annotation:
- The psa label syncer ignores user-based SCC decisions. This leads to issues, where the SCC is set to something less strict, but the syncer sees only restricted-v2.
Refactoring:
- The code is hard to read and some minor refactorings might lead to a future, where the code is more readable and we have one single function of doom handling validate and mutation.

CNTRLPLANE-179: set scc annotation min

---

pkg/securitycontextconstraints/sysctl/mustmatchpatterns.go

Previously, safe sysctl checks were using hardcoded kernel versions(e.g., "4.16"). This change replaces the hardcoded values with the corresponding utilkernel constants (e.g., `IPLocalReservedPortsNamespacedKernelVersion`).

NO-JIRA: Use utilkernel constants instead of hardcoded values for safe sysctls
